# Generated by Django 5.1.3 on 2024-11-20 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0002_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="reviewdb",
            name="grade",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1", "Відмінно"),
                    ("2", "Добре"),
                    ("3", "Нормально"),
                    ("4", "Погано"),
                    ("5", "Жахливо"),
                ],
                max_length=20,
                null=True,
                verbose_name="Оцінка",
            ),
        ),
        migrations.DeleteModel(
            name="Rating",
        ),
    ]
