# Generated by Django 5.1.3 on 2024-11-20 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0004_alter_reviewdb_grade"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reviewdb",
            name="text",
            field=models.TextField(blank=True, null=True, verbose_name="Текст"),
        ),
    ]
