# Generated by Django 5.1.3 on 2024-11-21 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0007_alter_reviewdb_grade"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reviewdb",
            name="grade",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (5, "Відмінно"),
                    (4, "Добре"),
                    (3, "Нормально"),
                    (2, "Погано"),
                    (1, "Жахливо"),
                ],
                null=True,
                verbose_name="Оцінка",
            ),
        ),
    ]
