# Generated by Django 5.1.3 on 2024-11-12 16:25

import django.db.models.deletion
import shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CategoryDB",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=150, verbose_name="Назва категорії"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="categories/",
                        verbose_name="Зображення",
                    ),
                ),
                ("slug", models.SlugField(blank=True, unique=True, verbose_name="URL")),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcategories",
                        to="shop.categorydb",
                        verbose_name="Категорія",
                    ),
                ),
            ],
            options={
                "verbose_name": "Категорія",
                "verbose_name_plural": "Категорії",
                "db_table": "category",
            },
        ),
        migrations.CreateModel(
            name="ProductDB",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Товар")),
                ("article", models.CharField(max_length=50, verbose_name="Артикул")),
                ("description", models.TextField(verbose_name="Опис")),
                ("info", models.TextField(verbose_name="Додаткова інформація")),
                ("price", models.PositiveIntegerField(verbose_name="Ціна")),
                (
                    "watched",
                    models.PositiveIntegerField(default=0, verbose_name="Перегляди"),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        blank=True, default=0, verbose_name="Кількість"
                    ),
                ),
                ("slug", models.SlugField(blank=True, unique=True, verbose_name="URL")),
                ("material", models.CharField(max_length=150, verbose_name="Матеріал")),
                ("color", models.CharField(max_length=150, verbose_name="Колір")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата створення"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата оновлення"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shop.categorydb",
                        verbose_name="Категорія",
                    ),
                ),
            ],
            options={
                "verbose_name": "Товар",
                "verbose_name_plural": "Товари",
                "db_table": "product",
            },
        ),
        migrations.CreateModel(
            name="Gallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        null=True,
                        upload_to=shop.models.product_image_path,
                        verbose_name="Зображення",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="shop.productdb",
                        verbose_name="Товар",
                    ),
                ),
            ],
            options={
                "verbose_name": "Зображення",
                "verbose_name_plural": "Галерея товарів",
                "db_table": "gallery",
            },
        ),
        migrations.CreateModel(
            name="SizeDB",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Розмір")),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sizes",
                        to="shop.categorydb",
                        verbose_name="Категорія",
                    ),
                ),
            ],
            options={
                "verbose_name": "Розмір",
                "verbose_name_plural": "Розміри",
                "db_table": "size",
            },
        ),
        migrations.CreateModel(
            name="ProductVariantDB",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stock_quantity",
                    models.PositiveIntegerField(default=0, verbose_name="Кількість"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="shop.productdb",
                        verbose_name="Товар",
                    ),
                ),
                (
                    "size",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="shop.sizedb",
                        verbose_name="Розмір",
                    ),
                ),
            ],
            options={
                "db_table": "product_variants",
            },
        ),
    ]
