# Generated by Django 5.1.3 on 2024-11-13 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0004_alter_productdb_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productdb",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="shop.categorydb",
                verbose_name="Категорія",
            ),
        ),
    ]
