# Generated by Django 5.1.3 on 2024-11-14 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0005_alter_productdb_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="categorydb",
            name="icon",
            field=models.ImageField(
                blank=True, null=True, upload_to="categories/icon/"
            ),
        ),
    ]
