# Generated by Django 5.1.3 on 2024-11-16 10:06

import shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0006_categorydb_icon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gallerydb",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=shop.models.product_image_path,
                verbose_name="Зображення",
            ),
        ),
    ]
