# Generated by Django 5.1.3 on 2024-11-16 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0007_alter_gallerydb_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productdb",
            name="article",
            field=models.CharField(max_length=50, unique=True, verbose_name="Артикул"),
        ),
    ]
