# Generated by Django 5.1.3 on 2024-11-23 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("shop", "0009_alter_productdb_slug"),
        ("users", "0002_customerdb"),
    ]

    operations = [
        migrations.CreateModel(
            name="CartDB",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Час створення"
                    ),
                ),
                (
                    "is_completed",
                    models.BooleanField(default=False, verbose_name="Завершено"),
                ),
                (
                    "shipping",
                    models.BooleanField(default=True, verbose_name="Доставка"),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="Покупець",
                        to="users.customerdb",
                    ),
                ),
            ],
            options={
                "verbose_name": "Замовлення",
                "verbose_name_plural": "Замовлення",
                "db_table": "cart",
            },
        ),
        migrations.CreateModel(
            name="CartItemDB",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        blank=True, default=0, null=True, verbose_name="Кількість"
                    ),
                ),
                (
                    "added_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Час додавання"
                    ),
                ),
                (
                    "cart",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cart_items",
                        to="cart.cartdb",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="shop.productdb",
                        verbose_name="Товар",
                    ),
                ),
            ],
            options={
                "verbose_name": "Товар в кошику",
                "verbose_name_plural": "Товари в кошику",
                "db_table": "cart_item",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("cart", "product"), name="unique_cart_products"
                    )
                ],
            },
        ),
    ]
