# Generated by Django 5.1.3 on 2024-11-24 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="cartitemdb",
            name="unique_cart_products",
        ),
    ]
