# Generated by Django 5.1.3 on 2024-11-25 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0002_remove_cartitemdb_unique_cart_products"),
        ("shop", "0009_alter_productdb_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitemdb",
            name="size",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cart_items",
                to="shop.sizedb",
                verbose_name="Розмір",
            ),
        ),
    ]
