# Generated by Django 5.1.3 on 2024-11-23 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cart", "0001_initial"),
        ("users", "0002_customerdb"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderAddressDB",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("index", models.PositiveIntegerField(verbose_name="Індекс")),
                ("city", models.CharField(max_length=255, verbose_name="Місто")),
                ("state", models.CharField(max_length=255, verbose_name="Район")),
                ("street", models.CharField(max_length=255, verbose_name="Вулиця")),
                ("created_at", models.DateTimeField(verbose_name="Час створення")),
                (
                    "cart",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="cart.cartdb",
                        verbose_name="Кошик",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="users.customerdb",
                        verbose_name="Покупець",
                    ),
                ),
            ],
            options={
                "verbose_name": "Адреса доставлення",
                "verbose_name_plural": "Адреса доставлення",
                "db_table": "order_address",
            },
        ),
    ]
