# Generated by Django 5.1.3 on 2024-11-24 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderaddressdb",
            name="state",
            field=models.CharField(max_length=255, verbose_name="Район/Область"),
        ),
    ]
