# Generated by Django 5.1.3 on 2024-12-03 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0002_alter_orderaddressdb_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderaddressdb",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Час створення"),
        ),
    ]
